### ISSUE TITLE
JSON Data Files Missing in JAR Build

### ISSUE THREAD

**Issue by sharpstorm** [AY2122S2-CS2103-W17-1/tp#191] opened 2022-03-18 09:13 UTC
## Synopsis
In the JAR build, the json data files were observed to not be created in the data folder. This issue is to be investigated.

**Comment by sharpstorm** [comment] 2022-03-19 16:36
I am unable to reproduce the issue.
Maybe the rest could also test if this is an issue, particularly @dandaandaaaaaan to see if its an issue specific to MacOS.

I want to note that no data files will be created until a command is run.

**Comment by dandaandaaaaaan** [comment] 2022-03-20 09:25
Just tested again and I think I've isolated the cause. Should be specific to Mac, the breakdown is as follows

- If the `.jar` file is run with the command `java -jar contax.jar` then it works fine, the data files are created normally

- However, if the file is run via just double clicking the `.jar` file, then the data files are saved on a system wide folder that I cannot find yet. The reason why this is system wide is that I've run the same file from multiple locations and it loads back the same data, so I believe data is saved in a hidden folder that I can't find where yet.

**Comment by dandaandaaaaaan** [comment] 2022-03-20 11:50
I think I cannot find where the stuff is being saved, but since the advised way for this module is to run the compiled `.jar` files with the proper command `java -jar contax.jar`, and that part works fine, I'll close this issue.

**Closed by dandaandaaaaaan** 2022-03-20 11:50 UTC
Labels: type.Bug, severity.High
